# =================================
# SORTIE A DOUALA CONFIGURATION
# =================================
server:
  servlet:
    context-path: /hair-salon-app

# =================================
# DATABASE && MULTIPART CONFIG
# =================================

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/hair_salon_db?createDatabaseIfNotExist=true&useSSL=true"
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  sql:
    init:
      encoding: UTF-8

  # *************************************
  # CONFIGURE MAIL
  #*************************************

#  mail:
#    default-encoding: UTF-8
#    host: smtp.gmail.com
#    username:
#    password: edhfepfvyzbvdvmd
#    port: 587
#    protocol: smtp
#    test-connection: false
#    properties:
#      mail:
#        smtp:
#          connectiontimeout: 5000
#          timeout: 5000
#          writetimeout: 5000
#          auth: true
#          starttls:
#            enable: true
app:
  auth:
    tokenSecret: hair_salon_app
    tokenExpirationMsec: 86400000 # 24H
    refreshTokenExpirationMsec: 604800000 # 168H
  global_username_email: hair_salon_app

